"""Added first migration

Revision ID: 10813866bae9
Revises: 
Create Date: 2023-03-01 03:05:25.121650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10813866bae9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Float(), nullable=True),
    sa.Column('quant', sa.Integer(), server_default='0', nullable=True),
    sa.Column('index', sa.String(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('title')
    )
    op.create_table('service_request',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('item_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flights', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('refundable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('validating_airline', sa.String(), nullable=True),
    sa.Column('pricing', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('service_request_uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['service_request_uuid'], ['service_request.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_data')
    op.drop_table('service_request')
    op.drop_table('currency')
    # ### end Alembic commands ###
